-- Insert default tags into the tags table
INSERT INTO tags (id, description, tag_group) VALUES
(1, 'Cross Stitch', 'stitching'),
(2, 'In The Hoop', 'stitching'),
(3, 'Filled', 'stitching'),
(4, 'Redwork', 'stitching'),
(5, 'Blackwork', 'stitching'),
(6, 'Stfumato', 'stitching'),
(7, 'Cutwork', 'stitching'),
(8, 'Don''t Know', 'image'),
(9, 'Line Outline', 'stitching'),
(10, 'Satin Stitch', 'stitching'),
(11, 'Applique', 'stitching'),
(12, 'Silhouette', 'image'),
(13, 'Light Fills', 'stitching'),
(14, 'Lace', 'stitching'),
(15, 'Trapunto', 'stitching'),
(16, 'For Quilting', 'image'),
(17, 'Handstitched Look', 'stitching'),
(18, 'Animals', 'image'),
(19, 'Flowers', 'image'),
(20, 'People and Work', 'image'),
(21, 'Job', 'image'),
(22, 'House', 'image'),
(23, 'Garden', 'image'),
(24, 'Music', 'image'),
(25, 'Nautical', 'image'),
(26, 'Landscapes and Travel', 'image'),
(27, 'Toys', 'image'),
(28, 'Hearts and Lips', 'image'),
(29, 'Sport', 'image'),
(30, 'Borders', 'image'),
(31, 'Paisley', 'image'),
(32, 'Butterflies and Insects', 'image'),
(33, 'Words and Letters', 'image'),
(34, 'Christmas', 'image'),
(35, 'Patterns', 'image'),
(36, 'Corners', 'image'),
(37, 'Bow and Ribbons', 'image'),
(38, 'Frames', 'image'),
(39, 'Trees', 'image'),
(40, 'Transport', 'image'),
(42, 'Birds', 'image'),
(43, 'Monsters', 'image'),
(44, 'Utility - Testing', 'image'),
(45, 'Food', 'image'),
(46, 'Scrolls', 'image'),
(47, 'Footwear', 'image'),
(48, 'For Clothes', 'image'),
(49, 'Faces', 'image'),
(50, 'Handbags', 'image'),
(51, 'Fairies, Elves etc.', 'image'),
(52, 'Hobbies', 'image'),
(53, 'Ornaments', 'image'),
(54, 'Collars', 'image'),
(55, 'Household', 'image'),
(56, 'Fashion', 'image'),
(57, 'Halloween', 'image'),
(58, 'Sun Moon and Stars', 'image'),
(59, 'Angels', 'image'),
(60, 'Babies', 'image'),
(61, 'Quilting', 'stitching'),
(62, 'Jewellery', 'image'),
(63, 'Buildings and Structures', 'image'),
(64, 'Crests', 'image'),
(65, 'Badges and Crests', 'image'),
(66, 'Fish and Seashells', 'image'),
(67, 'Flags', 'image'),
(68, 'Children', 'image'),
(69, 'Cartoon', 'image'),
(70, 'Banners', 'image'),
(71, 'Celebrations', 'image'),
(72, 'Ghosts', 'image'),
(73, 'Winter', 'image'),
(74, 'Zodiac', 'image'),
(75, 'Alphabets', 'image'),
(95, 'Cats', 'image'),
(96, 'Celtic and Tribal', 'image'),
(97, 'Dogs', 'image'),
(98, 'Diwali', 'image'),
(99, 'Easter', 'image'),
(100, 'Eid', 'image'),
(101, 'Fantasy', 'image'),
(102, 'Father''s Day', 'image'),
(103, 'Hanukkah', 'image'),
(104, 'Horses', 'image'),
(105, 'ITH Accessories', 'stitching'),
(106, 'Monogram', 'image'),
(107, 'Mother''s Day', 'image'),
(108, 'Religious', 'image'),
(109, 'Sketchy and Vintage', 'stitching'),
(110, 'Thanksgiving', 'image'),
(111, 'Valentine''s Day', 'image'),
(112, 'Wedding', 'image'),
(113, 'Wreaths', 'image'),
(114, 'Steampunk', 'image'),
(115, 'Sewing', 'image'),
(116, 'Clothes', 'image'),
(117, 'Netfill', 'stitching'),
(118, 'Dancing', 'image');
