<script>
  import { onMount } from "svelte";
  import DOMPurify from "dompurify";
  import { getAboutDocument } from "../api/commandAdapter";
  import { renderMarkdown } from "../utils/markdown.js";

  import primaryLicense from "../../LICENSE?raw";
  import rustLicencesHtml from "../assets/licences.html?raw";
  import npmLicencesDataRaw from "../assets/npm-licences.json";

  let { slug } = $props();

  /** @type {{ slug: string, title: string, description: string, filename: string, document_text: string } | null} */
  let documentItem = $state(null);
  let loading = $state(false);
  let error = $state("");

  /** Whether this instance is the dedicated Licence document route. */
  const isLicenceView = $derived(
    String(slug || "")
      .trim()
      .toLowerCase() === "licence"
  );

  /** @type {"application" | "rust" | "frontend"} */
  let activeLicenceTab = $state("application");

  /**
   * The Rust crate licence report generated by `cargo about`, sanitized once so
   * it can be injected via {@html} safely.
   */
  const sanitizedRustLicencesHtml = DOMPurify.sanitize(rustLicencesHtml, {
    USE_PROFILES: { html: true },
  });

  const hasRustLicences = sanitizedRustLicencesHtml.trim().length > 0;

  /**
   * Shape of a single NPM licence record emitted by `license-checker-rseidelsohn
   * --json`. All fields are optional because some emitted entries omit them.
   * @typedef {{ licenses?: string, repository?: string, publisher?: string, path?: string, licenseFile?: string, private?: boolean }} NpmLicenceRecord
   */

  /**
   * Convert the "name@version" -> record map emitted by license-checker into a
   * stable array of display rows for the {#each} block.
   * @param {Record<string, NpmLicenceRecord>} data
   * @returns {Array<{ name: string, version: string, licenses: string, repository: string }>}
   */
  function buildFrontendLicenceRows(data) {
    return Object.entries(data).map(([key, record]) => {
      const atIndex = key.lastIndexOf("@");
      const name = atIndex > 0 ? key.slice(0, atIndex) : key;
      const version = atIndex > 0 ? key.slice(atIndex + 1) : "";
      return {
        name,
        version,
        licenses: String(record.licenses || "Unknown"),
        repository: String(record.repository || ""),
      };
    });
  }

  /**
   * NPM package licence records keyed by "name@version". Converted once into a
   * stable array of display rows for the {#each}.
   * @type {Array<{ name: string, version: string, licenses: string, repository: string }>}
   */
  const frontendLicenceRows = buildFrontendLicenceRows(npmLicencesDataRaw);

  const hasFrontendLicences = frontendLicenceRows.length > 0;

  /** @param {"application" | "rust" | "frontend"} tab */
  function selectLicenceTab(tab) {
    activeLicenceTab = tab;
  }

  /**
   * Determine whether the loaded document should be rendered as Markdown.
   * @param {{ slug?: string, filename?: string } | null | undefined} item
   */
  function shouldRenderAsMarkdown(item) {
    if (!item || typeof item !== "object") return false;
    const slugName = String(item.slug || "").toLowerCase();
    const filename = String(item.filename || "").toLowerCase();
    return slugName === "ai-tagging" || filename.endsWith(".md");
  }

  /**
   * @param {{ slug?: string, filename?: string } | null | undefined} item
   */
  function shouldRenderAsHtml(item) {
    if (!item || typeof item !== "object") return false;
    const slugName = String(item.slug || "").toLowerCase();
    const filename = String(item.filename || "").toLowerCase();
    return slugName === "disclaimer" || filename.endsWith(".html");
  }

  /**
   * @param {string} slugName
   */
  async function loadAboutDocumentView(slugName) {
    const normalizedSlug = String(slugName || "")
      .trim()
      .toLowerCase();
    if (!normalizedSlug) {
      documentItem = null;
      error = "Document not found.";
      return;
    }

    loading = true;
    error = "";

    try {
      const result = await getAboutDocument(normalizedSlug);
      if (
        normalizedSlug !==
        String(slug || "")
          .trim()
          .toLowerCase()
      )
        return;

      documentItem = result?.item || null;
      if (!documentItem) {
        error = String(result?.error || "Document not found.");
      }
    } catch (e) {
      documentItem = null;
      error = `Could not load document: ${e}`;
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    // The dedicated Licence route renders its own 3-tab static content and
    // does not need to fetch a document from the backend.
    if (slug && !isLicenceView) {
      loadAboutDocumentView(slug);
    }
  });
</script>

{#if isLicenceView}
  <div class="max-w-5xl mx-auto space-y-4 font-sans">
    <div class="route-card rounded-xl shadow">
      <div class="border-b border-[var(--border-default)]">
        <nav class="flex gap-1 px-4 pt-3" aria-label="Licence information">
          <button
            type="button"
            class="px-4 py-2 text-sm font-semibold rounded-t border border-b-0 transition
              {activeLicenceTab === 'application'
              ? 'border-[var(--border-default)] bg-[var(--surface-card)] text-[var(--text-brand)]'
              : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--surface-hover)]'}"
            onclick={() => selectLicenceTab("application")}
          >
            Application Licence
          </button>
          <button
            type="button"
            class="px-4 py-2 text-sm font-semibold rounded-t border border-b-0 transition
              {activeLicenceTab === 'rust'
              ? 'border-[var(--border-default)] bg-[var(--surface-card)] text-[var(--text-brand)]'
              : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--surface-hover)]'}"
            onclick={() => selectLicenceTab("rust")}
          >
            Rust Dependencies
          </button>
          <button
            type="button"
            class="px-4 py-2 text-sm font-semibold rounded-t border border-b-0 transition
              {activeLicenceTab === 'frontend'
              ? 'border-[var(--border-default)] bg-[var(--surface-card)] text-[var(--text-brand)]'
              : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--surface-hover)]'}"
            onclick={() => selectLicenceTab("frontend")}
          >
            Frontend Dependencies
          </button>
        </nav>
      </div>

      <div class="p-5">
        {#if activeLicenceTab === "application"}
          <div data-testid="licence-application-tab">
            <div class="flex items-center justify-between gap-4 mb-4">
              <div>
                <h2 class="text-lg font-bold text-[var(--text-primary)] font-sans">
                  Application Licence
                </h2>
                <p class="text-sm text-[var(--text-secondary)] mt-1">
                  Embroidery Catalogue is licensed under
                  <strong> AGPL-3.0-or-later</strong>.
                </p>
              </div>
            </div>
            <pre
              class="whitespace-pre-wrap text-xs text-[var(--text-secondary)] bg-[var(--surface-card-subtle)] border border-[var(--border-default)] rounded-lg p-4 overflow-x-auto font-mono shadow-inner licence-primary-text">{primaryLicense}</pre>
          </div>
        {:else if activeLicenceTab === "rust"}
          <div data-testid="licence-rust-tab">
            <div class="flex items-center justify-between gap-4 mb-4">
              <div>
                <h2 class="text-lg font-bold text-[var(--text-primary)] font-sans">
                  Rust Dependencies
                </h2>
                <p class="text-sm text-[var(--text-secondary)] mt-1">
                  Open-source Rust crates used by the Embroidery Catalogue backend.
                </p>
              </div>
            </div>
            {#if hasRustLicences}
              <div class="licence-rust-list text-sm text-[var(--text-secondary)]">
                {@html sanitizedRustLicencesHtml}
              </div>
            {:else}
              <p class="text-sm text-[var(--text-muted)]">No Rust licence data is available.</p>
            {/if}
          </div>
        {:else}
          <div data-testid="licence-frontend-tab">
            <div class="flex items-center justify-between gap-4 mb-4">
              <div>
                <h2 class="text-lg font-bold text-[var(--text-primary)] font-sans">
                  Frontend Dependencies
                </h2>
                <p class="text-sm text-[var(--text-secondary)] mt-1">
                  Open-source NPM packages used by the Embroidery Catalogue frontend.
                </p>
              </div>
            </div>
            {#if hasFrontendLicences}
              <div class="space-y-2">
                {#each frontendLicenceRows as pkg}
                  <details
                    class="licence-card border border-[var(--border-default)] rounded-lg bg-[var(--surface-card-subtle)]"
                  >
                    <summary
                      class="licence-header px-4 py-3 cursor-pointer hover:bg-[var(--surface-hover)] transition"
                    >
                      <span class="font-medium text-[var(--text-primary)]">{pkg.name}</span>
                      {#if pkg.version}
                        <span class="text-[var(--text-muted)]"> (v{pkg.version})</span>
                      {/if}
                      <span
                        class="ml-2 text-xs font-semibold text-[var(--text-brand)] bg-[var(--surface-card)] border border-[var(--border-default)] rounded px-2 py-0.5"
                        >{pkg.licenses}</span
                      >
                    </summary>
                    <div
                      class="licence-crates px-4 pb-3 pt-2 border-t border-[var(--border-default)]"
                    >
                      <h4 class="ui-section-label font-semibold text-[var(--text-primary)] mb-1">
                        Licence
                      </h4>
                      <p class="text-sm text-[var(--text-secondary)]">{pkg.licenses}</p>
                      {#if pkg.repository}
                        <p class="text-sm mt-2">
                          <a
                            href={pkg.repository}
                            target="_blank"
                            rel="noopener noreferrer"
                            class="text-[var(--text-brand)] hover:underline font-medium break-all"
                            >{pkg.repository}</a
                          >
                        </p>
                      {/if}
                    </div>
                  </details>
                {/each}
              </div>
            {:else}
              <p data-testid="frontend-licences-empty" class="text-sm text-[var(--text-muted)]">
                No frontend packages recorded.
              </p>
            {/if}
          </div>
        {/if}
      </div>
    </div>
  </div>
{:else}
  <div class="max-w-5xl mx-auto space-y-4 font-sans">
    <div class="route-card rounded-xl shadow p-6">
      {#if loading}
        <p class="text-sm text-[var(--text-muted)]">Loading document...</p>
      {:else if error}
        <p class="text-sm text-red-650 bg-red-50 border border-red-200 rounded p-3">{error}</p>
      {:else if documentItem?.document_text}
        {#if shouldRenderAsHtml(documentItem)}
          <div
            class="text-sm text-gray-700 bg-gray-50 text-[var(--text-secondary)] bg-[var(--surface-card-subtle)] border border-[var(--border-default)] rounded-lg p-4 space-y-4 shadow-inner"
          >
            {@html documentItem.document_text}
          </div>
        {:else if shouldRenderAsMarkdown(documentItem)}
          <div
            class="text-sm text-gray-700 bg-gray-50 text-[var(--text-secondary)] bg-[var(--surface-card-subtle)] border border-[var(--border-default)] rounded-lg p-4 prose dark:prose-invert max-w-none shadow-inner document-markdown"
          >
            {@html renderMarkdown(documentItem.document_text)}
          </div>
        {:else}
          <pre
            class="whitespace-pre-wrap text-sm text-gray-700 bg-gray-50 text-[var(--text-secondary)] bg-[var(--surface-card-subtle)] border border-[var(--border-default)] rounded-lg p-4 overflow-x-auto font-mono shadow-inner">{documentItem.document_text}</pre>
        {/if}
      {:else}
        <p class="text-sm text-[var(--text-muted)] italic">Document content is unavailable.</p>
      {/if}
    </div>
  </div>
{/if}

<style>
  /* -----------------------------------------------------------------
   * Rust licence report (`cargo about` output injected via {@html}).
   * The generated markup uses .licenses-list / .license-card classes,
   * which are not Svelte-scoped, so style them via :global().
   * ----------------------------------------------------------------- */
  :global(.licence-rust-list .licenses-list) {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  :global(.licence-rust-list .license-card) {
    border: 1px solid var(--border-default);
    border-radius: 0.5rem;
    background-color: var(--surface-card-subtle);
    overflow: hidden;
  }

  :global(.licence-rust-list .license-header) {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    padding: 0.75rem 1rem;
    cursor: pointer;
    user-select: none;
  }

  :global(.licence-rust-list .license-header:hover) {
    background-color: var(--surface-hover);
  }

  :global(.licence-rust-list .license-name) {
    font-weight: 600;
    color: var(--text-primary);
  }

  :global(.licence-rust-list .license-used-by) {
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  :global(.licence-rust-list .license-crates) {
    padding: 0.75rem 1rem;
    border-top: 1px solid var(--border-default);
  }

  :global(.licence-rust-list .license-crates h4) {
    font-size: 0.8125rem;
    line-height: 1.2;
    font-weight: 600;
    margin: 0 0 0.375rem;
    color: var(--text-secondary);
  }

  :global(.licence-rust-list .license-crates ul) {
    margin: 0;
    padding-left: 1.25rem;
  }

  :global(.licence-rust-list .license-crates li) {
    font-size: 0.8125rem;
    line-height: 1.4;
    color: var(--text-secondary);
    margin: 0.25rem 0;
  }

  :global(.licence-rust-list .license-crates a) {
    color: var(--text-brand);
    text-decoration: underline;
    text-underline-offset: 2px;
    word-break: break-all;
  }

  :global(.licence-rust-list .license-text) {
    padding: 0.75rem 1rem;
    border-top: 1px solid var(--border-default);
  }

  :global(.licence-rust-list .license-text pre) {
    margin: 0;
    max-height: 24rem;
    overflow-y: auto;
    white-space: pre-wrap;
    word-break: break-word;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.75rem;
    line-height: 1.5;
    color: var(--text-secondary);
    background-color: var(--surface-preview);
    border: 1px solid var(--border-default);
    border-radius: 0.375rem;
    padding: 0.75rem;
  }

  /* -----------------------------------------------------------------
   * Injected {@html} Markdown is not Svelte-scoped, so target it via a
   * dedicated class with :global() selectors.
   * ----------------------------------------------------------------- */
  :global(.document-markdown h1) {
    font-size: 1.75rem;
    line-height: 1.25;
    font-weight: 700;
    margin: 0 0 0.75rem;
    color: var(--text-primary);
  }

  :global(.document-markdown h2) {
    font-size: 1.375rem;
    line-height: 1.3;
    font-weight: 650;
    margin: 1.5rem 0 0.5rem;
    padding-bottom: 0.25rem;
    border-bottom: 1px solid var(--border-default);
    color: var(--text-primary);
  }

  :global(.document-markdown h3) {
    font-size: 1.125rem;
    line-height: 1.35;
    font-weight: 650;
    margin: 1.25rem 0 0.5rem;
    color: var(--text-primary);
  }

  :global(.document-markdown h4) {
    font-size: 1rem;
    line-height: 1.4;
    font-weight: 650;
    margin: 1rem 0 0.5rem;
    color: var(--text-primary);
  }

  :global(.document-markdown p) {
    margin: 0.5rem 0;
  }

  :global(.document-markdown ul),
  :global(.document-markdown ol) {
    margin: 0.5rem 0 0.5rem 1.25rem;
    padding-left: 1rem;
  }

  :global(.document-markdown li) {
    margin: 0.25rem 0;
  }

  :global(.document-markdown blockquote) {
    margin: 0.75rem 0;
    padding-left: 0.75rem;
    border-left: 3px solid var(--border-focus);
    color: var(--text-secondary);
  }

  :global(.document-markdown a) {
    color: var(--text-brand);
    text-decoration: underline;
    text-underline-offset: 2px;
  }

  :global(.document-markdown code) {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.875em;
    background: var(--surface-card-subtle);
    color: var(--text-primary);
    border-radius: 0.25rem;
    padding: 0.125rem 0.25rem;
  }

  :global(.document-markdown pre) {
    margin: 0.75rem 0;
    padding: 0.75rem;
    border-radius: 0.375rem;
    background: var(--surface-card-subtle);
    color: var(--text-secondary);
    border: 1px solid var(--border-default);
    overflow-x: auto;
  }
</style>
