<script>
  import { onMount } from "svelte";
  import DOMPurify from "dompurify";
  import { getAboutDocument } from "../api/commandAdapter";
  import { renderMarkdown } from "../utils/markdown.js";

  import primaryLicense from "../../LICENSE?raw";
  import rustLicencesHtml from "../assets/licences.html?raw";
  import npmLicencesDataRaw from "../assets/npm-licences.json";

  let { slug } = $props();

  /** @type {{ slug: string, title: string, description: string, filename: string, document_text: string } | null} */
  let documentItem = $state(null);
  let loading = $state(false);
  let error = $state("");

  /** Whether this instance is the dedicated Licence document route. */
  const isLicenceView = $derived(
    String(slug || "")
      .trim()
      .toLowerCase() === "licence"
  );

  /** @type {"application" | "rust" | "frontend"} */
  let activeLicenceTab = $state("application");

  /**
   * The Rust crate licence report generated by `cargo about`, sanitized once so
   * it can be injected via {@html} safely.
   */
  const sanitizedRustLicencesHtml = DOMPurify.sanitize(rustLicencesHtml, {
    USE_PROFILES: { html: true },
  });

  const hasRustLicences = sanitizedRustLicencesHtml.trim().length > 0;

  /**
   * Shape of a single NPM licence record emitted by `license-checker-rseidelsohn
   * --json`. All fields are optional because some emitted entries omit them.
   * @typedef {{ licenses?: string, repository?: string, publisher?: string, path?: string, licenseFile?: string, private?: boolean }} NpmLicenceRecord
   */

  /**
   * Convert the "name@version" -> record map emitted by license-checker into a
   * stable array of display rows for the {#each} block.
   * @param {Record<string, NpmLicenceRecord>} data
   * @returns {Array<{ name: string, version: string, licenses: string, repository: string }>}
   */
  function buildFrontendLicenceRows(data) {
    return Object.entries(data).map(([key, record]) => {
      const atIndex = key.lastIndexOf("@");
      const name = atIndex > 0 ? key.slice(0, atIndex) : key;
      const version = atIndex > 0 ? key.slice(atIndex + 1) : "";
      return {
        name,
        version,
        licenses: String(record.licenses || "Unknown"),
        repository: String(record.repository || ""),
      };
    });
  }

  /**
   * NPM package licence records keyed by "name@version". Converted once into a
   * stable array of display rows for the {#each}.
   * @type {Array<{ name: string, version: string, licenses: string, repository: string }>}
   */
  const frontendLicenceRows = buildFrontendLicenceRows(npmLicencesDataRaw);

  const hasFrontendLicences = frontendLicenceRows.length > 0;

  /** @param {"application" | "rust" | "frontend"} tab */
  function selectLicenceTab(tab) {
    activeLicenceTab = tab;
  }

  /**
   * Determine whether the loaded document should be rendered as Markdown.
   * @param {{ slug?: string, filename?: string } | null | undefined} item
   */
  function shouldRenderAsMarkdown(item) {
    if (!item || typeof item !== "object") return false;
    const slugName = String(item.slug || "").toLowerCase();
    const filename = String(item.filename || "").toLowerCase();
    return slugName === "ai-tagging" || filename.endsWith(".md");
  }

  /**
   * @param {{ slug?: string, filename?: string } | null | undefined} item
   */
  function shouldRenderAsHtml(item) {
    if (!item || typeof item !== "object") return false;
    const slugName = String(item.slug || "").toLowerCase();
    const filename = String(item.filename || "").toLowerCase();
    return slugName === "disclaimer" || filename.endsWith(".html");
  }

  /**
   * @param {string} slugName
   */
  async function loadAboutDocumentView(slugName) {
    const normalizedSlug = String(slugName || "")
      .trim()
      .toLowerCase();
    if (!normalizedSlug) {
      documentItem = null;
      error = "Document not found.";
      return;
    }

    loading = true;
    error = "";

    try {
      const result = await getAboutDocument(normalizedSlug);
      if (
        normalizedSlug !==
        String(slug || "")
          .trim()
          .toLowerCase()
      )
        return;

      documentItem = result?.item || null;
      if (!documentItem) {
        error = String(result?.error || "Document not found.");
      }
    } catch (e) {
      documentItem = null;
      error = `Could not load document: ${e}`;
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    // The dedicated Licence route renders its own 3-tab static content and
    // does not need to fetch a document from the backend.
    if (slug && !isLicenceView) {
      loadAboutDocumentView(slug);
    }
  });
</script>

{#if isLicenceView}
  <div class="max-w-5xl mx-auto space-y-4 font-sans">
    <div class="bg-white rounded-xl shadow">
      <div class="border-b border-gray-200">
        <nav class="flex gap-1 px-4 pt-3" aria-label="Licence information">
          <button
            type="button"
            class="px-4 py-2 text-sm font-medium rounded-t-lg border border-b-0 transition
              {activeLicenceTab === 'application'
              ? 'bg-indigo-50 text-indigo-700 border-indigo-200'
              : 'text-gray-600 hover:text-gray-900 border-transparent hover:border-gray-300'}"
            onclick={() => selectLicenceTab("application")}
          >
            Application Licence
          </button>
          <button
            type="button"
            class="px-4 py-2 text-sm font-medium rounded-t-lg border border-b-0 transition
              {activeLicenceTab === 'rust'
              ? 'bg-indigo-50 text-indigo-700 border-indigo-200'
              : 'text-gray-600 hover:text-gray-900 border-transparent hover:border-gray-300'}"
            onclick={() => selectLicenceTab("rust")}
          >
            Rust Dependencies
          </button>
          <button
            type="button"
            class="px-4 py-2 text-sm font-medium rounded-t-lg border border-b-0 transition
              {activeLicenceTab === 'frontend'
              ? 'bg-indigo-50 text-indigo-700 border-indigo-200'
              : 'text-gray-600 hover:text-gray-900 border-transparent hover:border-gray-300'}"
            onclick={() => selectLicenceTab("frontend")}
          >
            Frontend Dependencies
          </button>
        </nav>
      </div>

      <div class="p-5">
        {#if activeLicenceTab === "application"}
          <div data-testid="licence-application-tab">
            <div class="flex items-center justify-between gap-4 mb-4">
              <div>
                <h2 class="text-lg font-bold text-gray-800 font-sans">Application Licence</h2>
                <p class="text-sm text-gray-600 mt-1">
                  Embroidery Catalogue is licensed under
                  <strong> AGPL-3.0-or-later</strong>.
                </p>
              </div>
            </div>
            <pre
              class="whitespace-pre-wrap text-xs text-gray-700 bg-gray-50 border rounded-lg p-4 overflow-x-auto font-mono shadow-inner licence-primary-text">{primaryLicense}</pre>
          </div>
        {:else if activeLicenceTab === "rust"}
          <div data-testid="licence-rust-tab">
            <div class="flex items-center justify-between gap-4 mb-4">
              <div>
                <h2 class="text-lg font-bold text-gray-800 font-sans">Rust Dependencies</h2>
                <p class="text-sm text-gray-600 mt-1">
                  Open-source Rust crates used by the Embroidery Catalogue backend.
                </p>
              </div>
            </div>
            {#if hasRustLicences}
              <div class="licence-rust-list text-sm text-gray-700">
                {@html sanitizedRustLicencesHtml}
              </div>
            {:else}
              <p class="text-sm text-gray-500">No Rust licence data is available.</p>
            {/if}
          </div>
        {:else}
          <div data-testid="licence-frontend-tab">
            <div class="flex items-center justify-between gap-4 mb-4">
              <div>
                <h2 class="text-lg font-bold text-gray-800 font-sans">Frontend Dependencies</h2>
                <p class="text-sm text-gray-600 mt-1">
                  Open-source NPM packages used by the Embroidery Catalogue frontend.
                </p>
              </div>
            </div>
            {#if hasFrontendLicences}
              <div class="space-y-2">
                {#each frontendLicenceRows as pkg}
                  <details class="licence-card border border-gray-200 rounded-lg bg-gray-50">
                    <summary
                      class="licence-header px-4 py-3 cursor-pointer hover:bg-gray-100 transition"
                    >
                      <span class="font-medium text-gray-800">{pkg.name}</span>
                      {#if pkg.version}
                        <span class="text-gray-500"> (v{pkg.version})</span>
                      {/if}
                      <span
                        class="ml-2 text-xs font-semibold text-indigo-700 bg-indigo-100 border border-indigo-200 rounded px-2 py-0.5"
                        >{pkg.licenses}</span
                      >
                    </summary>
                    <div class="licence-crates px-4 pb-3 pt-2 border-t border-gray-200">
                      <h4 class="ui-section-label font-semibold text-gray-850 mb-1">Licence</h4>
                      <p class="text-sm text-gray-700">{pkg.licenses}</p>
                      {#if pkg.repository}
                        <p class="text-sm mt-2">
                          <a
                            href={pkg.repository}
                            target="_blank"
                            rel="noopener noreferrer"
                            class="text-indigo-600 hover:underline font-medium break-all"
                            >{pkg.repository}</a
                          >
                        </p>
                      {/if}
                    </div>
                  </details>
                {/each}
              </div>
            {:else}
              <p data-testid="frontend-licences-empty" class="text-sm text-gray-500">
                No frontend packages recorded.
              </p>
            {/if}
          </div>
        {/if}
      </div>
    </div>
  </div>
{:else}
  <div class="max-w-5xl mx-auto space-y-4 font-sans">
    <div class="bg-white rounded-xl shadow p-6">
      {#if loading}
        <p class="text-sm text-gray-500">Loading document...</p>
      {:else if error}
        <p class="text-sm text-red-650 bg-red-50 border border-red-200 rounded p-3">{error}</p>
      {:else if documentItem?.document_text}
        {#if shouldRenderAsHtml(documentItem)}
          <div
            class="text-sm text-gray-700 bg-gray-50 border rounded-lg p-4 space-y-4 shadow-inner"
          >
            {@html documentItem.document_text}
          </div>
        {:else if shouldRenderAsMarkdown(documentItem)}
          <div
            class="text-sm text-gray-700 bg-gray-50 border rounded-lg p-4 prose prose-gray max-w-none shadow-inner document-markdown"
          >
            {@html renderMarkdown(documentItem.document_text)}
          </div>
        {:else}
          <pre
            class="whitespace-pre-wrap text-sm text-gray-700 bg-gray-50 border rounded-lg p-4 overflow-x-auto font-mono shadow-inner">{documentItem.document_text}</pre>
        {/if}
      {:else}
        <p class="text-sm text-gray-500 italic">Document content is unavailable.</p>
      {/if}
    </div>
  </div>
{/if}

<style>
  /* -----------------------------------------------------------------
   * Rust licence report (`cargo about` output injected via {@html}).
   * The generated markup uses .licenses-list / .license-card classes,
   * which are not Svelte-scoped, so style them via :global().
   * ----------------------------------------------------------------- */
  :global(.licence-rust-list .licenses-list) {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  :global(.licence-rust-list .license-card) {
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
    background-color: #f9fafb;
    overflow: hidden;
  }

  :global(.licence-rust-list .license-header) {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    padding: 0.75rem 1rem;
    cursor: pointer;
    user-select: none;
  }

  :global(.licence-rust-list .license-header:hover) {
    background-color: #f3f4f6;
  }

  :global(.licence-rust-list .license-name) {
    font-weight: 600;
    color: #1f2937;
  }

  :global(.licence-rust-list .license-used-by) {
    font-size: 0.75rem;
    color: #6b7280;
  }

  :global(.licence-rust-list .license-crates) {
    padding: 0.75rem 1rem;
    border-top: 1px solid #e5e7eb;
  }

  :global(.licence-rust-list .license-crates h4) {
    font-size: 0.8125rem;
    line-height: 1.2;
    font-weight: 600;
    margin: 0 0 0.375rem;
    color: #374151;
  }

  :global(.licence-rust-list .license-crates ul) {
    margin: 0;
    padding-left: 1.25rem;
  }

  :global(.licence-rust-list .license-crates li) {
    font-size: 0.8125rem;
    line-height: 1.4;
    color: #4b5563;
    margin: 0.25rem 0;
  }

  :global(.licence-rust-list .license-crates a) {
    color: #4f46e5;
    text-decoration: underline;
    text-underline-offset: 2px;
    word-break: break-all;
  }

  :global(.licence-rust-list .license-text) {
    padding: 0.75rem 1rem;
    border-top: 1px solid #e5e7eb;
  }

  :global(.licence-rust-list .license-text pre) {
    margin: 0;
    max-height: 24rem;
    overflow-y: auto;
    white-space: pre-wrap;
    word-break: break-word;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.75rem;
    line-height: 1.5;
    color: #374151;
    background-color: #ffffff;
    border: 1px solid #e5e7eb;
    border-radius: 0.375rem;
    padding: 0.75rem;
  }

  /* -----------------------------------------------------------------
   * Injected {@html} Markdown is not Svelte-scoped, so target it via a
   * dedicated class with :global() selectors. Tailwind Typography (the
   * "prose" classes) is not installed, so restore heading hierarchy and
   * vertical rhythm manually.
   * ----------------------------------------------------------------- */
  :global(.document-markdown h1) {
    font-size: 1.75rem;
    line-height: 1.25;
    font-weight: 700;
    margin: 0 0 0.75rem;
    color: #111827;
  }

  :global(.document-markdown h2) {
    font-size: 1.375rem;
    line-height: 1.3;
    font-weight: 650;
    margin: 1.5rem 0 0.5rem;
    padding-bottom: 0.25rem;
    border-bottom: 1px solid #e5e7eb;
    color: #1f2937;
  }

  :global(.document-markdown h3) {
    font-size: 1.125rem;
    line-height: 1.35;
    font-weight: 650;
    margin: 1.25rem 0 0.5rem;
    color: #1f2937;
  }

  :global(.document-markdown h4) {
    font-size: 1rem;
    line-height: 1.4;
    font-weight: 650;
    margin: 1rem 0 0.5rem;
    color: #1f2937;
  }

  :global(.document-markdown p) {
    margin: 0.5rem 0;
  }

  :global(.document-markdown ul),
  :global(.document-markdown ol) {
    margin: 0.5rem 0 0.5rem 1.25rem;
    padding-left: 1rem;
  }

  :global(.document-markdown li) {
    margin: 0.25rem 0;
  }

  :global(.document-markdown blockquote) {
    margin: 0.75rem 0;
    padding-left: 0.75rem;
    border-left: 3px solid #c7d2fe;
    color: #4b5563;
  }

  :global(.document-markdown a) {
    color: #4f46e5;
    text-decoration: underline;
    text-underline-offset: 2px;
  }

  :global(.document-markdown code) {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.875em;
    background: #f3f4f6;
    border-radius: 0.25rem;
    padding: 0.125rem 0.25rem;
  }

  :global(.document-markdown pre) {
    margin: 0.75rem 0;
    padding: 0.75rem;
    border-radius: 0.375rem;
    background: #1f2937;
    color: #e5e7eb;
    overflow-x: auto;
  }

  @media (prefers-color-scheme: dark) {
    :global(.licence-rust-list .license-card) {
      background-color: #1e293b;
      border-color: #334155;
    }

    :global(.licence-rust-list .license-header:hover) {
      background-color: #334155;
    }

    :global(.licence-rust-list .license-name) {
      color: #f1f5f9;
    }

    :global(.licence-rust-list .license-used-by) {
      color: #94a3b8;
    }

    :global(.licence-rust-list .license-crates) {
      border-top-color: #334155;
    }

    :global(.licence-rust-list .license-crates h4) {
      color: #e2e8f0;
    }

    :global(.licence-rust-list .license-crates li) {
      color: #cbd5e1;
    }

    :global(.licence-rust-list .license-crates a) {
      color: #818cf8;
    }

    :global(.licence-rust-list .license-text) {
      border-top-color: #334155;
    }

    :global(.licence-rust-list .license-text pre) {
      background-color: #0f172a;
      border-color: #334155;
      color: #cbd5e1;
    }

    :global(.document-markdown h1),
    :global(.document-markdown h2),
    :global(.document-markdown h3),
    :global(.document-markdown h4) {
      color: #f1f5f9;
    }

    :global(.document-markdown h2) {
      border-bottom-color: #334155;
    }

    :global(.document-markdown blockquote) {
      color: #cbd5e1;
      border-left-color: #6366f1;
    }

    :global(.document-markdown code) {
      background: #1e293b;
      color: #e2e8f0;
    }

    :global(.document-markdown a) {
      color: #818cf8;
    }
  }
</style>
