// Tests for the source module.
//
// This module was split out so the production file can stay focused
// on logic. It is included via a #[path] declaration in a
// #[cfg(test)] mod tests; module, retaining full access to the
// private items in the parent module through use super::*;.

use super::*;
use crate::models::StitchType;

#[test]
fn test_read_bean_jef_file() {
    let path = r"D:\My Software Development\Rust-Embroidery-Catalogue\tests\Test Designs\Bean.jef";
    let data = std::fs::read(path).expect("Failed to read test JEF file");
    let pattern = read_jef(&data).expect("Failed to parse JEF file");
    for (_i, _s) in pattern.stitches.iter().enumerate() {
        // (removed verbose per-stitch debug print)
    }
    assert_eq!(pattern.stitches.len(), 324, "Unexpected stitch count");
    let (min_x, min_y, max_x, max_y) = pattern.bounds();
    assert_eq!((max_x - min_x).abs() as i32, 500, "Unexpected width");
    assert_eq!((max_y - min_y).abs() as i32, 500, "Unexpected height");
    assert_eq!(
        pattern.stitches.first().map(|s| (s.x as i32, s.y as i32)),
        Some((-125, -125)),
        "Unexpected begin coords"
    );
    assert_eq!(
        pattern.stitches.last().map(|s| (s.x as i32, s.y as i32)),
        Some((-250, -250)),
        "Unexpected end coords"
    );
    assert_eq!(pattern.count_threads(), 1, "Unexpected thread changes");
    assert_eq!(
        pattern.count_color_changes(),
        0,
        "Unexpected colour changes"
    );
}

#[test]
fn test_read_jef_synthetic_large_fixture() {
    // Read the SyntheticLarge.jef fixture generated by
    // `examples/gen_jef_fixture.rs`.  The design spans
    // (-50, -50) -> (750, 250) â†’ width 800, height 300.
    let path = r"D:\My Software Development\Rust-Embroidery-Catalogue\tests\Test Designs\SyntheticLarge.jef";
    let data = std::fs::read(path).expect("Failed to read SyntheticLarge.jef fixture");
    let pattern = read_jef(&data).expect("Failed to parse SyntheticLarge.jef");

    // --- Same assertions as the removed Bear Mask test ------------------
    assert!(
        !pattern.stitches.is_empty(),
        "Expected stitches in synthetic large design"
    );
    assert!(
        pattern.count_stitch_commands(StitchType::Stitch) > 0,
        "Expected drawable stitches in synthetic large design"
    );

    let (min_x, min_y, max_x, max_y) = pattern.bounds();
    let width = (max_x - min_x).abs();
    let height = (max_y - min_y).abs();
    assert!(
        width > 700.0,
        "Expected wider than 70mm in deci-mm units, got {width}"
    );
    assert!(
        height > 250.0,
        "Expected taller than 25mm in deci-mm units, got {height}"
    );

    let first = pattern.stitches.first().expect("Expected first stitch");
    assert!(
        first.x != 0.0 || first.y != 0.0,
        "Unexpected origin-anchored first stitch in synthetic design"
    );

    // Precise assertions matching the fixture's known layout
    assert!(
        (width - 800.0).abs() < f32::EPSILON,
        "Expected exact width of 800 deci-mm, got {width}"
    );
    assert!(
        (height - 300.0).abs() < f32::EPSILON,
        "Expected exact height of 300 deci-mm, got {height}"
    );
    assert_eq!(first.x, -50.0, "First stitch x should be -50");
    assert_eq!(first.y, -50.0, "First stitch y should be -50");
    assert_eq!(
        pattern.count_stitch_commands(StitchType::Stitch),
        15,
        "Expected exactly 15 regular stitches"
    );
}
#[test]
fn test_read_jef_two_stitches() {
    // Build a minimal JEF file with no colour table and two regular stitches.
    //
    // Header layout (116 bytes):
    //   0..4   stitch_offset  u32 LE  â†’  116 (data starts right after header)
    //   4..24  _pad1          [u8;20]
    //   24..28 count_colors   u32 LE  â†’  0
    //   28..116 _pad2         [u8;88]
    //
    // Stitch 1: dx=5, dy=10  â†’ bytes [0x05, 0xF6]
    //   signed8(0x05)=5,  signed8(0xF6)=246-256=-10, dy = -(-10) = 10
    // Stitch 2: dx=-3, dy=7 â†’ bytes [0xFD, 0xF9]
    //   signed8(0xFD)=253-256=-3, signed8(0xF9)=249-256=-7, dy = -(-7) = 7
    //
    // Expected cumulative coordinates from origin (0,0):
    //   stitch_1 â†’ (5, 10)
    //   stitch_2 â†’ (2, 17)
    //   + automatic END appended by read_jef

    let stitch_offset: u32 = 116;
    let mut data = Vec::with_capacity(120);

    // --- header ---
    data.extend_from_slice(&stitch_offset.to_le_bytes()); // stitch_offset
    data.extend_from_slice(&[0u8; 20]); // _pad1
    data.extend_from_slice(&0u32.to_le_bytes()); // count_colors = 0
    data.extend_from_slice(&[0u8; 88]); // _pad2

    // --- stitch data ---
    data.push(0x05); // stitch 1 dx
    data.push(0xF6); // stitch 1 dy
    data.push(0xFD); // stitch 2 dx
    data.push(0xF9); // stitch 2 dy

    let pattern = read_jef(&data).expect("should parse a valid minimal JEF");

    // Two regular Stitch entries + the mandatory End
    assert_eq!(
        pattern.count_stitch_commands(StitchType::Stitch),
        2,
        "expected exactly 2 regular stitches"
    );

    let stitches: Vec<_> = pattern
        .stitches
        .iter()
        .filter(|s| s.stitch_type == StitchType::Stitch)
        .collect();

    assert_eq!(stitches.len(), 2);
    assert_eq!(stitches[0].x, 5.0);
    assert_eq!(stitches[0].y, 10.0);
    assert_eq!(stitches[1].x, 2.0);
    assert_eq!(stitches[1].y, 17.0);

    // The parser always appends End
    assert_eq!(pattern.count_stitch_commands(StitchType::End), 1);

    // No thread entries (count_colors was 0)
    assert!(pattern.threadlist.is_empty());
}

#[test]
fn test_read_jef_jump_opcode_maps_to_jump() {
    let stitch_offset: u32 = 116;
    let mut data = Vec::with_capacity(124);

    // Header with zero color entries.
    data.extend_from_slice(&stitch_offset.to_le_bytes());
    data.extend_from_slice(&[0u8; 20]);
    data.extend_from_slice(&0u32.to_le_bytes());
    data.extend_from_slice(&[0u8; 88]);

    // Jump command: 0x80 0x02 + delta bytes.
    data.extend_from_slice(&[0x80, 0x02, 0x05, 0xF9]);
    // End command: 0x80 0x10 + ignored delta bytes.
    data.extend_from_slice(&[0x80, 0x10, 0x00, 0x00]);

    let pattern = read_jef(&data).expect("should parse JEF jump command");

    assert_eq!(pattern.count_stitch_commands(StitchType::Jump), 1);
    assert_eq!(pattern.count_stitch_commands(StitchType::Stitch), 0);

    let jump = pattern
        .stitches
        .iter()
        .find(|s| s.stitch_type == StitchType::Jump)
        .expect("expected jump stitch");
    assert_eq!(jump.x, 5.0);
    assert_eq!(jump.y, 7.0);
}

#[test]
fn test_read_jef_color_change_preserves_nonzero_movement() {
    // Stitch data begins after 116-byte header plus two i32 color entries.
    let stitch_offset: u32 = 124;
    let mut data = Vec::with_capacity(140);

    // Header with two color entries so 0x80 0x01 is treated as ColorChange.
    data.extend_from_slice(&stitch_offset.to_le_bytes());
    data.extend_from_slice(&[0u8; 20]);
    data.extend_from_slice(&2u32.to_le_bytes());
    data.extend_from_slice(&[0u8; 88]);
    data.extend_from_slice(&1i32.to_le_bytes());
    data.extend_from_slice(&2i32.to_le_bytes());

    // Regular stitch to move to (10, 0).
    data.extend_from_slice(&[0x0A, 0x00]);
    // Color change with non-zero movement dx=5, dy=3.
    data.extend_from_slice(&[0x80, 0x01, 0x05, 0xFD]);
    // One more regular stitch dx=2, dy=0 -> should end at (17, 3).
    data.extend_from_slice(&[0x02, 0x00]);

    let pattern = read_jef(&data).expect("should parse JEF color change movement");

    assert_eq!(pattern.count_stitch_commands(StitchType::ColorChange), 1);
    assert_eq!(pattern.count_stitch_commands(StitchType::Jump), 1);

    let jump = pattern
        .stitches
        .iter()
        .find(|s| s.stitch_type == StitchType::Jump)
        .expect("expected jump emitted for color-change movement");
    assert_eq!(jump.x, 15.0);
    assert_eq!(jump.y, 3.0);

    let last_stitch = pattern
        .stitches
        .iter()
        .rev()
        .find(|s| s.stitch_type == StitchType::Stitch)
        .expect("expected final stitch command");
    assert_eq!(last_stitch.x, 17.0);
    assert_eq!(last_stitch.y, 3.0);
}

#[test]
fn test_read_jef_empty_data_returns_error() {
    let data: &[u8] = &[];
    let result = read_jef(data);
    assert!(result.is_err(), "empty data should fail header parsing");
}

#[test]
fn test_read_jef_truncated_header() {
    // Fewer than the 116-byte fixed header.
    let data: Vec<u8> = vec![0u8; 50];
    let result = read_jef(&data);
    assert!(result.is_err(), "truncated header should fail binrw parse");
}

#[test]
fn test_read_jef_truncated_mid_stitch() {
    // Valid 116-byte header with no colors, then one complete stitch (2 bytes)
    // and one truncated stitch (only 1 byte of the pair).
    let stitch_offset: u32 = 116;
    let mut data = Vec::with_capacity(120);

    data.extend_from_slice(&stitch_offset.to_le_bytes());
    data.extend_from_slice(&[0u8; 20]);
    data.extend_from_slice(&0u32.to_le_bytes());
    data.extend_from_slice(&[0u8; 88]);

    // Complete stitch: dx=5, dy=10
    data.push(0x05);
    data.push(0xF6);
    // Truncated stitch: only 1 byte present.
    data.push(0xFD);

    let pattern = read_jef(&data).expect("should handle truncated JEF stitch data");

    // The one complete stitch should have been retained.
    assert_eq!(pattern.count_stitch_commands(StitchType::Stitch), 1);

    let stitches: Vec<_> = pattern
        .stitches
        .iter()
        .filter(|s| s.stitch_type == StitchType::Stitch)
        .collect();
    assert_eq!(stitches[0].x, 5.0);
    assert_eq!(stitches[0].y, 10.0);

    // End marker appended at the last decoded position (5, 10).
    assert_eq!(pattern.count_stitch_commands(StitchType::End), 1);
    let end = pattern.stitches.last().expect("expected End marker");
    assert_eq!(end.x, 5.0);
    assert_eq!(end.y, 10.0);
}

#[test]
fn test_signed8_jef_boundaries() {
    // signed8 maps an unsigned byte to the signed range [-128, 127].
    assert_eq!(signed8(0), 0);
    assert_eq!(signed8(127), 127);
    assert_eq!(signed8(128), -128);
    assert_eq!(signed8(129), -127);
    assert_eq!(signed8(255), -1);
}

#[test]
fn test_read_jef_stitch_signed8_extremes() {
    // The byte 0x80 is reserved as the control-command escape, so regular
    // stitch deltas are limited to signed8 range minus 0x80:
    //   max   = +127 (0x7F)
    //   min   = -127 (0x81)
    //
    // Valid 116-byte header with no colors, two stitches at signed8 extremes.
    let stitch_offset: u32 = 116;
    let mut data = Vec::with_capacity(124);

    data.extend_from_slice(&stitch_offset.to_le_bytes());
    data.extend_from_slice(&[0u8; 20]);
    data.extend_from_slice(&0u32.to_le_bytes());
    data.extend_from_slice(&[0u8; 88]);

    // Stitch 1: dx = signed8(0x7F) = +127, dy = -signed8(0xFF) = -(-1) = +1
    data.push(0x7F);
    data.push(0xFF);
    // Stitch 2: dx = signed8(0x81) = -127, dy = -signed8(0x00) = 0
    data.push(0x81);
    data.push(0x00);

    let pattern = read_jef(&data).expect("should parse signed8 extreme JEF stitches");

    let stitches: Vec<_> = pattern
        .stitches
        .iter()
        .filter(|s| s.stitch_type == StitchType::Stitch)
        .collect();
    assert_eq!(stitches.len(), 2);
    // Stitch 1 ends at (127, 1)
    assert_eq!(stitches[0].x, 127.0);
    assert_eq!(stitches[0].y, 1.0);
    // Stitch 2 accumulates to (0, 1)
    assert_eq!(stitches[1].x, 0.0);
    assert_eq!(stitches[1].y, 1.0);

    assert_eq!(pattern.count_stitch_commands(StitchType::End), 1);
}
